#!/bin/bash

stop() {
	sudo killall node
	sudo killall grunt
	sudo service mongod stop 
	echo 'Service stopped' >&2
}
start() {
	cd myville-backend; node "app.js" &
	cd myville-backend; sudo service mongod start &
	cd ../myville-frontend/; grunt serve &
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
esac
