#!/bin/bash

stop() {
	sudo killall node
	sudo killall grunt
	sudo killall mongod
	echo 'Service stopped' >&2
}
start() {
	cd myville-backend; sudo service mongod start &
	wait
	node "app.js" &
	cd ../myville-frontend/; grunt serve &
}
restart() {
	sudo killall node
	sudo killall grunt
	wait
	cd myville-backend;
	node "app.js" &
	cd ../myville-frontend/; grunt serve &
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
esac
